package be.butskri.playground.documentatie.domain.main;

import java.util.ArrayList;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

public class RemoveDuplicatesAndSort {

    public static void main(String[] args) {
        List<String> list = setUpList();

        SortedSet<String> sortedSet = new TreeSet<>(list);
        print(sortedSet);
    }

    private static void print(SortedSet<String> sortedSet) {
        sortedSet.stream().forEach(System.out::println);
    }

    public static ArrayList<String> setUpList() {
        ArrayList<String> strings = new ArrayList<>();
        strings.add("Architecture");
        strings.add("GUI");
        strings.add("Devops");
        strings.add("Design patterns");
        strings.add("Decision making");
        strings.add("Elasticsearch");
        strings.add("Development - Full stack");
        strings.add("Security");
        strings.add("Containerization");
        strings.add("Axon");
        strings.add("Leadership");
        strings.add("Reactive programming");
        strings.add("Containerization");
        strings.add("Microservices");
        strings.add("JDK");
        strings.add("Development - Full Stack");
        strings.add("Microservices");
        strings.add("Spring boot");
        strings.add("Javascript / Typescript");
        strings.add("Security - SSL");
        strings.add("Jira");
        strings.add("Java");
        strings.add("Softskills");
        strings.add("Axon");
        strings.add("Java");
        strings.add("Spring Web Mvc");
        strings.add("GUI");
        strings.add("Spring boot");
        strings.add("Security - SSL");
        strings.add("Devops");
        strings.add("Microservices");
        strings.add("Axon");
        strings.add("Microservices");
        strings.add("GUI Testing");
        strings.add("Aspects");
        strings.add("Spring boot");
        strings.add("Functional programming");
        strings.add("Devops");
        strings.add("Security");
        strings.add("Security");
        strings.add("AI");
        strings.add("Queues");
        strings.add("Spring boot");
        strings.add("Groovy");
        strings.add("Linux");
        strings.add("GUI - Angular");
        strings.add("GUI");
        strings.add("JPA");
        strings.add("Spring boot");
        strings.add("Javascript / Typescript");
        strings.add("GUI - Angular");
        strings.add("Spring REST");
        strings.add("Linux");
        strings.add("Security - SSL");
        strings.add("Microservices");
        strings.add("Security");
        strings.add("Presentations");
        strings.add("???");
        strings.add("Containerization");
        strings.add("Containerization");
        strings.add("Spring boot");
        strings.add("Git");
        strings.add("Axon");
        strings.add("CQRS");
        strings.add("CQRS");
        strings.add("Axon");
        strings.add("Axon");
        strings.add("Development - Full Stack");
        strings.add("???");
        strings.add("Development - Full Stack");
        strings.add("Devops");
        strings.add("Transactions");
        strings.add("Spring boot");
        strings.add("GUI Testing");
        strings.add("Axon");
        strings.add("Containerization");
        strings.add("Containerization");
        strings.add("Transactions");
        strings.add("Microservices");
        strings.add("JDK");
        strings.add("Testing");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("???");
        strings.add("Design");
        strings.add("Devops");
        strings.add("Containerization");
        strings.add("Cloud");
        strings.add("Design patterns");
        strings.add("Leadership");
        strings.add("Devops");
        strings.add("Spring");
        strings.add("Development - Full Stack");
        strings.add("Design patterns");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("GUI - charts");
        strings.add("Java");
        strings.add("Java");
        strings.add("API Design");
        strings.add("Microservices");
        strings.add("Containerization");
        strings.add("GUI");
        strings.add("GUI");
        strings.add("Cloud");
        strings.add("Testing");
        strings.add("REST");
        strings.add("Captcha");
        strings.add("Testing");
        strings.add("Spring boot");
        strings.add("Microservices");
        strings.add("Estimations");
        strings.add("Java");
        strings.add("Microservices");
        strings.add("REST");
        strings.add("Devops - dashboard");
        strings.add("REST");
        strings.add("Security - TSL");
        strings.add("Axon");
        strings.add("Elasticsearch");
        strings.add("GUI Testing");
        strings.add("Event-driven");
        strings.add("Charts");
        strings.add("General - Tools");
        strings.add("Architecture");
        strings.add("Security");
        strings.add("REST");
        strings.add("Spring boot");
        strings.add("Security - Encryption");
        strings.add("Development - Full Stack");
        strings.add("Contracts");
        strings.add("???");
        strings.add("Security - JWT");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("???");
        strings.add("Containerization");
        strings.add("Aspects");
        strings.add("Logging");
        strings.add("Microservices");
        strings.add("REST");
        strings.add("Cloud");
        strings.add("Microservices");
        strings.add("Development - Full Stack");
        strings.add("Networks");
        strings.add("Development - Full Stack");
        strings.add("Microservices");
        strings.add("Cloud");
        strings.add("CQRS");
        strings.add("Simple code");
        strings.add("Architecture");
        strings.add("Agile");
        strings.add("Containerization");
        strings.add("Spring Security");
        strings.add("Spring boot");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("GUI");
        strings.add("GUI Testing");
        strings.add("Containerization");
        strings.add("Microservices");
        strings.add("Design patterns");
        strings.add("Development - Full Stack");
        strings.add("GUI - Angular");
        strings.add("Algorithms");
        strings.add("GUI Testing");
        strings.add("Cloud");
        strings.add("Testing");
        strings.add("Spring Security");
        strings.add("Containerization");
        strings.add("GUI Testing");
        strings.add("SQL");
        strings.add("???");
        strings.add("Containerization");
        strings.add("REST");
        strings.add("Spring MVC");
        strings.add("Devops - dashboard");
        strings.add("Transactions");
        strings.add("Event-driven");
        strings.add("GUI");
        strings.add("Javascript / Typescript");
        strings.add("Debugging");
        strings.add("Microservices");
        strings.add("SQL");
        strings.add("Spring boot");
        strings.add("Microservices");
        strings.add("Java");
        strings.add("Microservices");
        strings.add("Software quality");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("Microservices");
        strings.add("Spring boot");
        strings.add("REST");
        strings.add("Spring");
        strings.add("Containerization");
        strings.add("GUI - Angular");
        strings.add("Books");
        strings.add("JDK");
        strings.add("Tools");
        strings.add("Devops - Monitoring");
        strings.add("Gamification");
        strings.add("Document-generation");
        strings.add("Cloud");
        strings.add("Containerization");
        strings.add("Spring boot");
        strings.add("Microservices");
        strings.add("Cloud");
        strings.add("Microservices");
        strings.add("Containerization");
        strings.add("JPA");
        strings.add("Event-driven");
        strings.add("JPA");
        strings.add("Career");
        strings.add("Containerization");
        strings.add("Spring boot");
        strings.add("Architecture");
        strings.add("Spring boot");
        strings.add("Java");
        strings.add("Linux");
        strings.add("Security");
        strings.add("Javascript / Typescript");
        strings.add("Security - Authentication");
        strings.add("Security - Authentication");
        strings.add("Security - Authentication");
        strings.add("Protocols - RSocket");
        strings.add("Spring boot");
        strings.add("Security");
        strings.add("Design patterns");
        strings.add("Performance");
        strings.add("Spring boot");
        strings.add("Security - Authentication");
        strings.add("Performance");
        strings.add("Containerization");
        strings.add("Spring boot");
        strings.add("Spring boot");
        return strings;
    }

}
